name: VnuaSchedule
description: "A Schedule project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  speech_to_text: ^7.0.0
  sqflite: ^2.3.3
  flutter_tts: ^3.8.3
  http: ^1.2.2
  intl: ^0.20.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.0
  table_calendar: ^3.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_localizations:
  sdk: flutter
  intl: ^0.18.0
flutter:
  uses-material-design: true


  assets:
    - .env